### ISSUE TITLE
Channel Details sidebar: cannot see Members except on hover

### ISSUE THREAD

**Issue by rmohns** [mallowigi/slack-one-dark-theme#1]
Looks like the Member list's font color needs to change, as member names only show on hover:

![Channel info color glitch](https://user-images.githubusercontent.com/2131133/48085195-9fc48c80-e1c7-11e8-94b5-d6212fce9878.png)

(There's also that odd white bar at the top of the screen.)

Context: Mac Slack app, v3.3.3, no other modifications.

**Comment by proshin-roman** [comment]
I faced with the same issue on Windows 10.

**Comment by mallowigi** [comment]
Guys I'm not working on this project anymore. If you want to issue a PR for this you're welcome.
