### ISSUE TITLE
Permission denied applying the them on MacOS 10.14.5

### ISSUE THREAD

**Issue by hanhpv** [mallowigi/slack-one-dark-theme#10]
? Please select an command Apply theme
Adding One Dark Theme Code to Slack...

(node:10482) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, copyfile '/Applications/Slack.app/Contents/Resources/app.asar' -> '/Applications/Slack.app/Contents/Resources/app.asar.backup'
    at Object.copyFileSync (fs.js:1731:3)
    at Object.exports.apply (/Users/hans/Projects/slack-one-dark-theme/lib/command.js:39:6)
    at exports.execute (/Users/hans/Projects/slack-one-dark-theme/lib/command.js:67:12)
    at main (/Users/hans/Projects/slack-one-dark-theme/main.js:19:3)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:10482) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10482) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mallowigi** [comment]
You need to run the script with sudo

**Comment by hanhpv** [comment]
I don't often run a script dowloaded from the Internet as sudo. Will it have a side effect, just for sure?

**Comment by hanhpv** [comment]
<img width="970" alt="Screen Shot 2019-07-22 at 5 54 33 PM" src="https://user-images.githubusercontent.com/5069672/61627388-d4bb3580-aca9-11e9-97c4-6f48ce5ab927.png">
Does not look very good to me with Slack version 4.0.0 :(
