### ISSUE TITLE
Npm apply method does not work on Linux

### ISSUE THREAD

**Issue by tylermanning** [mallowigi/slack-one-dark-theme#12]
The path that was hardcoded for linux is incorrect. I had to update it but even after updating and running it "successfully" the slack app remains the same color.

**Comment by mallowigi** [comment]
The method to theme stopped working. I don't know if it's still possible. 

https://slack.engineering/rebuilding-slack-on-the-desktop-308d6fe94ae4?source=collection_home---4------0-----------------------&gi=37d81d672375
