### ISSUE TITLE
How to change color for when you tag a user

### ISSUE THREAD

**Issue by vinhdoanprocurify** [mallowigi/slack-one-dark-theme#2]
Thanks for this its awesome! Just a quick question, how do i change the color of the tagged user? It's white right now. 

When I do @channel, that color seems to be changeable, but not when you tag a specific user.

See attachment.

![image](https://user-images.githubusercontent.com/37004118/48237686-9fb9bd80-e37c-11e8-94ac-15ed46599cbe.png)

Thanks in advance!

**Comment by mallowigi** [comment]
I'm not working on this project anymore. You're welcome to do PR though
