### ISSUE TITLE
CSS changes are not impacting the Threads page

### ISSUE THREAD

**Issue by maddprof** [mallowigi/slack-one-dark-theme#4]
The changes aren't impacting the Threads page - it's still white background with the altered colors.

**Comment by mallowigi** [comment]
Can you post a screenshot?

**Comment by maddprof** [comment]
![image](https://user-images.githubusercontent.com/20006281/57396500-857c6300-7198-11e9-9457-a8b0d9031903.png)

See attached. You can see that there is a white bar along the top as well (this also happens in the thread frame that pops out from the right hand side).

**Comment by gkillough** [comment]
Any update on this?

**Comment by knwpsk** [comment]
That's the Search results, not the Threads pane - right?  Maybe you should edit the ticket headline.
