### ISSUE TITLE
app.asar.unpacked folder doesn't contain src folder in version 4.0.0 anymore

### ISSUE THREAD

**Issue by Adnanhaddad96** [mallowigi/slack-one-dark-theme#6]
... and because of that the theme won't show up after updating. Hope you guys can fix this asap. Thank you!

**Comment by hernancmartinez** [comment]
+1

**Comment by duredhel13** [comment]
+ 1

**Comment by mallowigi** [comment]
I issued a hotfix very very quickly. Please clone this repository and run the npm script "apply".

Currently works only for Mac.

I'll update the readme at some point

**Comment by Adnanhaddad96** [comment]
Could you please let us know when you find a fix for Windows too?

Thanks!

**Comment by jamesrichard91** [comment]
When I run "npm run apply" I get this error
```Adding One Dark Theme Code to Slack... 
fs.js:1878
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'callback', 'function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "callback" argument must be of type function
    at Object.fs.copyFile (fs.js:1878:11)
    at Object.<anonymous> (/Applications/slack-one-dark-theme/apply.js:69:4)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

What version of npm should I be using?

**Comment by gkillough** [comment]
I had to add a callback to line 69: 
```
// Make a backup
fs.copyFile(SLACK_ARCHIVE, `${SLACK_RESOURCES_DIR}/app.asar.backup`, function(err, data) {
    if (err) throw err;
});
```
Then I ran into a mis-named variable on line 74. I changed `SLACK_RESOURCES_ARCHIVE` to `SLACK_ARCHIVE` and everything worked.

Note: `SLACK_RESOURCES_DIR` uses `Slack\ Copy.app`.

**Comment by mallowigi** [comment]
https://slack.engineering/rebuilding-slack-on-the-desktop-308d6fe94ae4?source=collection_home---4------0-----------------------&gi=37d81d672375
