### ISSUE TITLE
cssPath in apply.js is returning Error 404

### ISSUE THREAD

**Issue by hernancmartinez** [mallowigi/slack-one-dark-theme#7]
This path doesn't exist: `https://raw.githubusercontent.com/mallowigi/slack-one-dark-theme/master/custom.css` .

It returns error 404 Not Found

**Comment by mallowigi** [comment]
right........ I need more work on this. bear with me

**Comment by tekdahl** [comment]
Just got moved into styles, wasn't sure if it was intended so I didn't want to make a pr to your readme or anything for it
https://raw.githubusercontent.com/mallowigi/slack-one-dark-theme/master/styles/custom.css
