### ISSUE TITLE
Applied theme in 4.0 looks real bad in Windows

### ISSUE THREAD

**Issue by dsoverby1986** [mallowigi/slack-one-dark-theme#8]
I followed the theme installation instruction for Slack 4.0 and the theme was successfully update with no errors, but it looks terrible...

![2019-07-18 02_01_16-](https://user-images.githubusercontent.com/7773023/61433087-5b65c080-a900-11e9-8809-872483edfc3d.png)

Background is dark but text is unchanged. Message backgrounds turn white on hover.

**Comment by mallowigi** [comment]
Yes, for some reason, in Windows it looks awful. I will try to find time to understand why.

**Comment by Saucistophe** [comment]
Same on linux (mint). :penguin:

**Comment by dsoverby1986** [comment]
> Yes, for some reason, in Windows it looks awful. I will try to find time to understand why.

Thanks!

Love the work you're doing here.

I just miss my dark theme so badly.
![bitmoji](https://render.bitstrips.com/v2/cpanel/204d8f0d-50e5-4db5-a810-f6525a68dc39-dddc7538-1211-42b4-b5a7-ad31dadfdcbf-v1.png?transparent=1&palette=1&width=246)

**Comment by trejder** [comment]
This is not the problem with this repo, but with Slack itself. Do the full Slack reset and after that this style will look great. Simply, use `Help -> Troubleshoot -> Reset Slack` to have the theme fully applied.

For details see [this pull request](https://github.com/mallowigi/slack-one-dark-theme/pull/9) or [the source of this information](https://github.com/leoandreotti/slack-dark-theme#important-note).

**Comment by pbloigu** [comment]
> This is not the problem with this repo, but with Slack itself. Do the full Slack reset and after that this style will look great. Simply, use `Help -> Troubleshoot -> Reset Slack` to have the theme fully applied.
> 
> For details see [this pull request](https://github.com/mallowigi/slack-one-dark-theme/pull/9) or [the source of this information](https://github.com/leoandreotti/slack-dark-theme#important-note).

I can confirm that resetting Slack works.  (the menu entry is `Help -> Troubleshooting -> Reset App Data`). Thanks!

**Comment by trejder** [comment]
I have crafted a short memo about this: http://onezeronull.com/2019/07/19/dark-theme-in-slack-4/

**Comment by kumamonishe** [comment]
Thing is, I have to Reset App Data each time I laucnh slack to apply the theme.

**Comment by mallowigi** [comment]
Maybe it’s time to just let it go and stick to the default theme 😔

**Comment by pbloigu** [comment]
> Thing is, I have to Reset App Data each time I laucnh slack to apply the theme.

Well I don't have to do that: the dark theme is there even after restarting Slack. What I did was: reset app data, quit Slack, apply this theme, start Slack. Then, even if I restart Slack, the theme is still applied.

**Comment by trejder** [comment]
Either you did some magic or followed some secret combination that I cannot reproduce. I think I have repeated your step exactly as you wrote and still nothing. Each time I start Slack, theme is applied, but looks as awfully as in the initial comment in here (i.e. most things not readable). Each time I have to reset data to get Slack looking correctly.

**Comment by FireRx** [comment]
Thanks for the help. For now this works fine

**Comment by trejder** [comment]
Would be nice to know exact steps you both undertook to have this working fine. Because some of us are still struggling with this issue and are still forced to reset Slack data each time Slack is started, in order to get dark theme in slack. So, congrats on success, but for part of us this doesn't work fine.

**Comment by pbloigu** [comment]
Yeah, I know, sorry. I'll get back on this as soon as possible. I'll even uninstall Slack and repeat the process on a clean install.

**Comment by FireRx** [comment]
trejder, I had to do the same as you, I just leave slack running all the time so I don't need to reset as often unless I reboot.  hopeful a fix will be shortcoming.

**Comment by kumamonishe** [comment]
I've got no idea where to ask (or how to debug electron apps) so I'll try to ask here: what css tag defines the background color of the div block which surrounds user name when you mention some user with "@"?

**Comment by trejder** [comment]
@kumamonishe Slack runs in web browser as well. And 99% uses the same layout and style sheet as the packed Electron version. So, simply run Slack web version in your browser and debug whatever you need using standard browser's debug / developers tools.

**Comment by pbloigu** [comment]
> Yeah, I know, sorry. I'll get back on this as soon as possible. I'll even uninstall Slack and repeat the process on a clean install.

Alright guys, here's what I did:

1. Uninstall Slack
2. Delete `%USERPROFILE%\Appdata\Local\Slack`
3. Reinstall Slack
4. Quit Slack
5. `git clone https://github.com/mallowigi/slack-one-dark-theme.git`
6. `npm install`
7. `npm run apply`
8. Apply the theme
9. Start Slack (looks awful)
10. Reset app data
11. Theme looks as it should.

Then I rebooted the machine and started Slack -> the theme is still fine.
So I don't know what I'm doing wrong here :) I'm running Windows 10 Pro.

A couple of things to consider though: before applying the theme did you guys really **quit** Slack or just hit the X at the top right corner, as it doesn't quit the app, it just minimizes it to the tray. 

And btw, you can see the developer tools in Slack too, just add the environment variable `SLACK_DEVELOPER_MENU` with the value `true`, and restart Slack. Then, you can summon the dev tools by hitting Ctrl+Alt+I. I have that env variable set, but I doubt it has any effect on this issue.

**Comment by mallowigi** [comment]
Just updated the styles a bit. I'm redoing it from scratch, but it is taking a hellova time.

Don't know about the Windows/Linux workaround though, but anyway try to run "update theme" to take the latest changes.

**Comment by trejder** [comment]
@pbloigu Then there must be something really weird in my PC or in my installation of Slack or something really unusual at your side. I have followed your guide step-by-step (thank you for providing it!) and unfortunately see no difference. Cool looking dark theme says only until next Slack restart.

I think I am going to give up on this thing. Bastards at Slack did a really good job in preventing us from using dark theme and keeping our eyes in comfort. I think I learn to live with the fact that I need to reset Slack data (which particularly means -- login again) each time I start this damn application.

**Comment by pbloigu** [comment]
Alright, how about enabling the dev tools, just for the heck of it? I know it's a long shot, but I have it enabled. I won't have an access to my laptop for a few days, so can't try disabling.

**Comment by trejder** [comment]
I am not sure, if enabling dev tools in Slack would bring me any closer to answering the question "Why dark theme isn't replicated each time I restart Slack?" or "Why do I have to reset all my data each time I restart Slack to get dark theme working?". 

I think that dev tools are rather for dark theme's author to check some elements that needs additional styling in order to turn them into dark versions.

If you have any suggestion on how I should use dev tools to resolve problem with not applied dark style then I will be more than happy to hear it. Because, I am right now out of options and out of ideas.

**Comment by mallowigi** [comment]
FYI https://www.reddit.com/r/Slack/comments/cesgjb/dont_update_to_the_newest_version_of_slack_no/

**Comment by Tiberriver256** [comment]
I just want you to know @trejder. You are not alone. I have the same issue.

**Comment by mallowigi** [comment]
https://slack.engineering/rebuilding-slack-on-the-desktop-308d6fe94ae4?source=collection_home---4------0-----------------------&gi=37d81d672375
